[package]
name = "profig"
version = "0.1.0"
edition = "2021"

[dependencies]
profig-macros = { path = "./profig-macros" }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"

[dependencies.proc-macro2]
version = "1"
